<div class="matter">
    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <a href="<?php echo $this->baseUrl('admin/faqs/save')?>" class="btn btn-default">Add New Faqs</a>
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left">Tables</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <table class="table table-bordered ">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Question</th>
                                <th>Status</th>
                                <th>Control</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                $stt = 1;
                                foreach($this->faqs as $faq):
                            ?>
                            <tr>
                                <td><?php echo $stt;?></td>
                                <td><?php echo $faq['faq_question']?></td>
                                <td><?php echo ($faq['faq_status'] == 1)?'Hiện':'Ẩn';?></td>


                                <td>

                                    <a class="btn btn-sm btn-warning"  title="Edit" href="<?php echo $this->baseUrl('admin/faqs/edit/id/').$faq['faq_id'];?>"><i class="fa fa-pencil"></i> </a>
                                    <a class="btn btn-sm btn-danger"  title="Delete" href="<?php echo $this->baseUrl('admin/faqs/delete/id/').$faq['faq_id'];?>" onclick="return confirm('Are you sure?')"><i class="fa fa-times"></i> </a>
                                </td>
                            </tr>
                            <?php $stt++;endforeach;?>
                            </tbody>
                        </table>
                    </div>
                    <div class="widget-foot">

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

