<div class="matter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left">Forms</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <div class="padd">

                            <h6>Input Boxs</h6>
                            <hr />
                            <!-- Form starts.  -->
                            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->baseUrl('admin/faqs/save')?>">
                                <?php if($this->items): ?>
                                <?php foreach($this->items as $error):?>
                                <div class="alert alert-warning">
                                    <?php echo $error?>
                                </div>
                                <?php endforeach;?>
                                <?php endif;?>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">Input Box</label>
                                    <div class="col-md-8">
                                        <input type="text" class="form-control" placeholder="Input Box" name="faq_question">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label">RadioBox</label>
                                    <div class="col-md-8">
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="faq_status" id="hien" value="1" checked>
                                                Hiện
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="faq_status" id="an" value="0">
                                                Ẩn
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-2 control-label">Answer</label>
                                    <div class="col-md-8">
                                        <textarea class="form-control ckeditor" rows="3" placeholder="Textarea" name="faq_answer"></textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-lg-2"><?php echo __('STT')?></label>
                                    <div class="col-lg-7">
                                        <input type="text" class="form-control" id="sitename" name="faq_sort" value="0">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-8">

                                        <input type="submit" class="btn btn-success" value="Add New Question"/>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/ Matter ends -->