<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left">Page Heading 
        <!-- page meta -->
        <span class="page-meta">Something Goes Here</span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="index.html"><i class="fa fa-home"></i> Home</a> 
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="#" class="bread-current">Dashboard</a>
    </div>
    <div class="clearfix"></div>
</div><!--/ Page heading ends -->

<!-- Matter -->
<div class="matter">
    <div class="container-fluid">
        <div class="row-fluid">

            <!-- Content -->
            <h3><?php echo __FILE__; ?></h3>
            <h1><?php echo __('message'); ?></h1>

        </div>
    </div>
</div><!--/ Matter ends -->