<div class="left col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <form>
        <h4>THE BUTCHERY</h4>
        <quote><?php echo __('Please fill in your details') ?></quote>
        <div class="col-md-6 left-left col-sm-12 col-xs-12 ">
            <label><?php echo __('First Name') ?></label>
            <input type="text"/>
            <label><?php echo __('Contact No') ?></label>
            <input type="text"/>
            <label><?php echo __('Gender') ?></label>
            <input type="text"/>
        </div>
        <div class="col-md-6 left-right col-sm-12 col-xs-12">

            <label><?php echo __('Last Name') ?></label>
            <input type="text"/>
            <label><?php echo __('Email Address') ?></label>
            <input type="text"/>
            <label><?php echo __('Participants(2-6)') ?></label>
            <input type="text"/>
            <input type="submit" value="SUBMIT"/>
        </div>
    </form>
</div>
<div class="right col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <div class="info">
        <h4><?php echo __('SUMMARY') ?></h4>
        <ul>
            <li><span>Game:The Butchery</span>
            <li>
            <li><span>Date:</span>
            <li>
            <li><span>Time:</span>
            <li>
            <li><span>Participant:</span>
            <li>
            <li><span>Total price:</span>
            <li>
        </ul>
        <i>*Please arive 10 mins before you booking time</i>
    </div>

</div>

