<h4>THE BUTCHERY</h4>
<p class="desc-booking-detail">Please select your perferred time</p>

<div class="schedule-container week hidden-xs">
    <div class="row mmb schedule-bar">
        <div class="col-xs-12 col-sm-3 col-md-2">
            <a href="#" class="btn schedule-control prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-8 text-center">
            <span class="schedule-week">26/10-1/11</span>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-2 text-right">
            <a href="#" class="btn schedule-control next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <table class="table table-responsive">
        <thead>

            <tr>
                <td><p>Sun</p><p>(26/10/2014)</p></td>
                <td><p>Mon</p><p>(27/10/2014)</p></td>
                <td><p>Tue</p><p>(28/10/2014)</p></td>
                <td><p>Wed</p><p>(29/10/2014)</p></td>
                <td><p>Thu</p><p>(30/10/2014)</p></td>
                <td><p>Fri</p><p>(31/10/2014)</p></td>
                <td><p>Sat</p><p>(32/10/2014)</p></td>
            </tr>
            <tr class="space"></tr>
        </thead>
        <tbody>
            <tr align="center">
                <td><a href="#">10:45</a></td>
                <td><a href="#">10:45</a></td>
                <td class="acti"><a href="#">10:45</a></td>
                <td><a href="#">10:45</a></td>
                <td><a href="#">10:45</a></td>
                <td><a href="#">10:45</a></td>
                <td><a href="#">10:45</a></td>
            </tr>
            <tr class="space"></tr>
            <tr align="center">
                <td><a href="#">12:00</a></td>
                <td><a href="#">12:00</a></td>
                <td class="reserved">Reserved</td>
                <td><a href="#">12:00</a></td>
                <td><a href="#">12:00</a></td>
                <td><a href="#">12:00</a></td>
                <td><a href="#">12:00</a></td>
            </tr>
            <tr class="space"></tr>
            <tr align="center">
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
                <td><a href="#">13:15</a></td>
            </tr>
            <tr class="space"></tr>
            <tr align="center">
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
                <td><a href="#">14:30</a></td>
            </tr>
            <tr class="space"></tr>
            <tr align="center">
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
                <td><a href="#">15:45</a></td>
            </tr>
        </tbody>
    </table>
</div><!-- schedule-container -->
<div class="schedule-container day visible-xs">
    <div class="row mmb schedule-bar">
        <div class="col-xs-5">
            <a href="#" class="btn schedule-control prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </div>
        <div class="col-xs-2 text-center">
            <span class="schedule-week"></span>
        </div>
        <div class="col-xs-5 text-right">
            <a href="#" class="btn schedule-control next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <td><p>Sun</p><p>(26/10/2014)</p></td>
            </tr>
        </thead>

        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="acti">10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="reserved">Reserved</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>

    </table>
</div><!-- schedule-container day visible-xs -->