<?php
$curGame = $this->curGame;
?>
<h4><?php echo __($curGame[0]['game_name']) ?></h4>
<input type="hidden" id="cur_game_id" value="<?php echo $curGame[0]['game_id'] ?>"/>
<p class="desc-booking-detail"><?php echo __('Please select your perferred time') ?></p>

<div id="times-content">
    <script type="text/javascript" language="javascript">
        jQuery(document).ready(function () {
            var cd = "<?php echo date('d-m-Y'); ?>";
            BookingController.getTimes(cd, 0);
        });
    </script>
</div>
