<?php
$aryTimes = $this->aryTime;
$aryWeek = $this->curWeek;
?>
<h4>THE BUTCHERY</h4>
<p class="desc-booking-detail">Please select your perferred time</p>

<div class="schedule-container week hidden-xs">
    <div class="row mmb schedule-bar">
        <div class="col-xs-12 col-sm-3 col-md-2">
            <a href="#" class="btn schedule-control prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-8 text-center">
            <span class="schedule-week">
                <?php echo date('d/m', strtotime(date('d-m-Y'))) . ' - ' . date('d/m', strtotime(date('d-m-Y') . ' +6 day ')); ?>
            </span>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-2 text-right">
            <a href="#" class="btn schedule-control next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <table class="table table-responsive">
        <thead>

        <tr>
            <?php foreach ($aryWeek as $_day => $_date): ?>
                <td>
                    <p><?php echo $_day ?></p>

                    <p><?php echo '(' . $_date . ')' ?></p>
                </td>
            <?php endforeach; ?>
        </tr>
        <tr class="space"></tr>
        </thead>
        <tbody>
        <?php foreach ($aryTimes as $_time): ?>
            <tr align="center">
                <?php for ($i = 1; $i <= 7; $i++) { ?>
                    <td>
                        <a href="#"><?php echo date('h:i', strtotime($_time['time'])); ?></a>
                    </td>
                <?php } ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div><!-- schedule-container -->
<div class="schedule-container day visible-xs">
    <div class="row mmb schedule-bar">
        <div class="col-xs-5">
            <a href="#" class="btn schedule-control prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
        </div>
        <div class="col-xs-2 text-center">
            <span class="schedule-week"></span>
        </div>
        <div class="col-xs-5 text-right">
            <a href="#" class="btn schedule-control next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr>
            <td><p>Sun</p>

                <p>(26/10/2014)</p></td>
        </tr>
        </thead>

        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="acti">10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>
        <tr>
            <td class="reserved">Reserved</td>
        </tr>
        <tr>
            <td>10:45</td>
        </tr>

    </table>
</div><!-- schedule-container day visible-xs -->