<?php
$aryGames = $this->aryGames;
?>
<?php if (!$aryGames || empty($aryGames)): ?>
    <p><?php echo __('No game found'); ?></p>
<?php else: ?>
    <div id="booking-container">
        <?php foreach ($aryGames as $_game): ?>
            <?php
            if($_game['game_image']){
                $gameImg = $this->baseUrl('public/upload/').$_game['game_image'];
            }else{
                $gameImg = $this->baseUrl('public/upload/no_img.jpg');
            }
            if($_game['game_difficult']){
                $gameDif = (int)$_game['game_difficult'];
            }else{
                $gameDif = "N/A";
            }
            ?>
            <div class="item-booking col-md-6">
                <a href="#">
                    <img src="<?php echo $gameImg ?>" alt="item booking" class="img-item" width="244px" height="313px"/>
                </a>

                <div class="media-body">
                    <a href="#"><h4><?php echo $_game['game_name']; ?></h4></a>

                    <p>
                        <?php echo $_game['game_desc'] ?>
                    </p>
                <span>
                    <?php echo __('Difficulty: ') ?>
                    <?php for($i = 1; $i <= $gameDif; $i ++): ?>
                        <img src="<?php echo  $this->baseUrl('public/upload/difficult.png')?>"/>
                    <?php endfor; ?>
                </span>
                    <a onclick="BookingController.getTimes('<?php echo date('d-m-Y'); ?>',0,'<?php echo $_game['game_id'] ?>')"
                       class="btn-book"><?php echo __('Book Now') ?></a>
                </div>

            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
