<?php
$linkStart = $this->currentUrl . '/page/' . $this->first;

$linkPrevious = '#';
if (isset($this->previous))
{
    $linkPrevious = $this->currentUrl . '/page/' . $this->previous;
}
$linkNext = '#';
if (isset($this->next))
{
    $linkNext = $this->currentUrl . '/page/' . $this->next;
}

$linkEnd = $this->currentUrl . '/page/' . $this->last;

$strPage = '';
foreach ($this->pagesInRange as $key)
{
    if ($this->current == $key)
    {
        $strPage .= '<li><a href="javascript:void(0)" class="current_page">' . $key . '</a></li>';
    }
    else
    {
        $linkPage = $this->currentUrl . '/page/' . $key;
        $strPage .= '<li><a href="' . $linkPage . '">' . $key . '</a></li>';
    }
}

$page = __('page') . ' ' . $this->current . ' ' . __('of') . ' ' . $this->last;
?>
<div class="div-pagination">
    <ul class="pagination">
        <li><a href="<?php echo $linkStart; ?>"><?php echo __('start') ?></a></li>
        <li><a href="<?php echo $linkPrevious; ?>"><?php echo __('prev') ?></a></li>
        <?php echo $strPage ?>
        <li><a href="<?php echo $linkNext; ?>"><?php echo __('next'); ?></a></li>
        <li><a href="<?php echo $linkEnd; ?>"><?php echo __('end') ?></a></li>
        <li><?php echo $page ?></li>
    </ul>    
</div>
<style>
    .current_page{
        background: #a69a9a !important;
    }
</style>