<!--TrangVT-->
<?php
$pricesCollection = $this->pricesCollection;
$no= 1;
?>
<div class="page-head">
    <h2 class="pull-left"><?php echo __('prices table') ?></h2>
</div>

<div class="matter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
                    <div class="alert alert-success">
                        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                            <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
                    <div class="alert alert-warning">
                        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                            <?php echo $msg ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left"><?php echo __('prices table') ?></div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                            <a href="<?php echo $this->baseUrl('admin/prices/update'); ?>" class=""><?php echo __('add new price')?></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <table class="table table-bordered ">
                            <thead>
                            <tr>
                                <th><?php echo __('STT')?></th>
                                <th><?php echo __('prices type')?></th>
                                <th><?php echo __('prices desc')?></th>
                                <th><?php echo __('prices')?></th>
                                <th><?php echo __('status')?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($pricesCollection as $price):?>
                                <?php
                                if($price['price_status'] == 1){
                                    $class = 'label-success';
                                    $priceStatus = __('enable');
                                    $href = $this->baseUrl('admin/prices/updatestatus/id/'.$price['price_id'].'/status/0');
                                }else{
                                    $class = 'label-important';
                                    $priceStatus = __('disable');
                                    $href = $this->baseUrl('admin/prices/updatestatus/id/'.$price['price_id'].'/status/1');
                                }
                                ?>
                                <tr>
                                    <td><?php echo $no ?></td>
                                    <td><?php echo $price['price_name'] ?></td>
                                    <td><?php echo $price['price_desc'] ?></td>
                                    <td><?php echo $price['price_value'] ?></td>
                                    <td><a href="<?php echo $href ?>"><span class="label <?php echo $class?>"><?php echo $priceStatus ?></span></a></td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="<?php echo $this->baseUrl('admin/prices/update/id/'.$price['price_id']); ?>" class="btn btn-sm btn-warning">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++ ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="widget-foot">
                        <?php
                        $currentUrl = $this->baseUrl($this->currentController.'/index');
                        echo $this->paginationControl($this->pagination, 'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                        ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/ Matter ends -->
