<!--TrangVT-->
<?php
echo 111;
echo $this->id;
?>
<div class="col-md-7">
    <!-- Quick setting -->
    <div class="widget wviolet">
        <div class="widget-head">
            <div class="pull-left"><?php echo __('add new price')?></div>
            <div class="widget-icons pull-right">
                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                <a href="#" class="wclose"><i class="fa fa-times"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="widget-content">
            <div class="padd">

                <div class="form quick-post">
                    <!-- Quick setting form (not working)-->
                    <form class="form-horizontal" role="form" action="<?php echo $this->baseUrl('admin/prices/add'); ?>" method="post">
                        <!-- Name -->
                        <div class="form-group">
                            <label class="control-label col-md-2" for="sitename"><?php echo __('prices type')?></label>
                            <div class="col-md-7">
                                <input type="text" class="form-control" id="sitename" placeholder="Metro King">
                            </div>
                        </div>
                        <!-- description -->
                        <div class="form-group">
                            <label class="control-label col-lg-2" for="sitedescription"><?php echo __('prices desc')?></label>
                            <div class="col-lg-7">
                                <textarea class="form-control" id="sitedescription"></textarea>
                            </div>
                        </div>
                        <!-- User role Format -->
                        <div class="form-group">
                            <label class="control-label col-lg-2"><?php echo __('prices')?></label>
                            <div class="col-lg-7">
                                <select class="form-control">
                                    <option value='option1'>Author</option>
                                    <option value='option2'>Moderator</option>
                                    <option value='option3'>Editor</option>
                                </select>
                            </div>
                        </div>

                        <!-- Buttons -->
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-9 col-lg-offset-2">
                                <button type="submit" class="btn btn-info">Save Now</button>
                                <button type="reset" class="btn btn-default">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>


</div>