<h3>RULE</h3>
<p>
    In a team of 2-5 people, you will be locked in a custom designed, captivating and

    pulse-raising environment, in which you will attempt to solve many riddles

    and puzzles in place. Unlocking the room’s mysteries will lead you to the final 

    key to escape. To facilitate your quest, we will allow you 2 hints at anytime during

    the game. REMEMBER: to emerge a winner, you have to complete the quest in 45 

    minutes! It’s a race against the clock!
</p>
<span class="note"><i>For more info: <a href="<?php echo $this->baseUrl('faqs')?>">Check FAQ</a></i></span>
<p>
    We have 4 room themes at the moment: The Butchery, Haunted Hotel, Mega

    Nerd and Save Santa. Each theme is carefully crafted to cover you the entire

    emotional spectrum from shock and frantic to thrill and accomplished.
</p>