<!--TrangVT-->
<div class="page-head">
<h2 class="pull-left">Times</h2>
</div>

<div class="matter">
<div class="container">
<div class="row">
    <div class="col-md-12">
        <div class="widget wviolet">
            <div class="widget-head">
                <div class="pull-left">Games</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <table class="table table-bordered ">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Control</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>3</td>
                        <td>Kumar Ragu</td>
                        <td><span class="label label-success">Active</span></td>
                        <td>
                            <div class="btn-group">
                                <button class="btn btn-sm btn-default"><i class="fa fa-check"></i> </button>
                                <button class="btn btn-sm btn-default"><i class="fa fa-pencil"></i> </button>
                                <button class="btn btn-sm btn-default"><i class="fa fa-times"></i> </button>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="widget-foot">
                <ul class="pagination pull-right">
                    <li><a href="#">Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
</div>
</div><!--/ Matter ends -->

<?php
$muser=new Admin_Model_Games();
echo "<pre>";
print_r($muser->getAllGame());
echo "</pre>";