<!--TrangVT-->
<?php
$timesCollection = $this->timesCollection;
$countRecord = count($timesCollection);
$no= 1;
?>
<?php if($countRecord):?>
    <div class="page-head">
        <h2 class="pull-left"><?php echo __('times table') ?>
            <span class="page-meta"><?php echo __('manage time')?></span>
        </h2>
    </div>

    <div class="matter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
                    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
                        <div class="alert alert-success">
                            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                                <?php echo $msg ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($flashMessenger->setNamespace('fail')->hasMessages()): ?>
                        <div class="alert alert-warning">
                            <?php foreach ($flashMessenger->getMessages() as $msg): ?>
                                <?php echo $msg ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div class="widget wred">
                        <div class="widget-head">
                            <div class="pull-left"><?php echo __('times table') ?></div>
                            <div class="widget-icons pull-right">
                                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                                <a href="<?php echo $this->baseUrl('admin/times/update'); ?>" class=""><?php echo __('add new time')?></a>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="widget-content">
                            <table class="table table-bordered ">
                                <thead>
                                <tr>
                                    <th><?php echo __('STT')?></th>
                                    <th><?php echo __('times')?></th>
                                    <th><?php echo __('status')?></th>
                                    <th><?php echo __('weekend')?></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach($timesCollection as $times):?>
                                    <?php
                                    if($times['time_status'] == 1){
                                        $class = 'label-success';
                                        $timeStatus = __('enable');
                                        $href = $this->baseUrl('admin/times/updatestatus/id/'.$times['time_id'].'/status/0');
                                    }else{
                                        $class = 'label-important';
                                        $timeStatus = __('disable');
                                        $href = $this->baseUrl('admin/times/updatestatus/id/'.$times['time_id'].'/status/1');
                                    }
                                    ?>
                                    <tr>
                                        <td><?php echo $no ?></td>
                                        <td><?php echo $times['time'] ?></td>
                                        <td><a href="<?php echo $href ?>"><span class="label <?php echo $class?>"><?php echo $timeStatus ?></span></a></td>
                                        <td><?php if($times['is_weekend']){echo __('yes');}else{echo __('no');} ?></td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="<?php echo $this->baseUrl('admin/times/update/id/'.$times['time_id']); ?>" class="btn btn-sm btn-warning">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                            </div>
                                            <a href="<?php echo $this->baseUrl('admin/times/delete/id/'.$times['time_id']); ?>"><div class="btn btn-sm btn-danger"><i class="fa fa-times"></i></div></a>
                                        </td>
                                    </tr>
                                    <?php $no++ ?>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="widget-foot">
                            <?php
                            $currentUrl = $this->baseUrl($this->currentController.'/index');
                            echo $this->paginationControl($this->pagination, 'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                            ?>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/ Matter ends -->
<?php else: ?>
    <div class="matter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="widget wred">
                        <div class="widget-head">
                            <div class="pull-left"><a href="<?php echo $this->baseUrl('admin/times/update'); ?>" class=""><?php echo __('add new time')?></a></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>