<!--TrangVT-->
<?php
$games = new Admin_Model_Games();
$gamesCollection = $games->getAllGames();
$count = count($gamesCollection);
$id = 1;
?>
<div class="page-head">
<h2 class="pull-left"><?php echo __('times') ?></h2>
</div>

<div class="matter">
<div class="container">
<div class="row">
    <div class="col-md-12">
        <div class="widget wviolet">
            <div class="widget-head">
                <div class="pull-left"><?php echo __('games') ?></div>
                <div class="widget-icons pull-right">
<!--                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>-->
<!--                    <a href="#" class="wclose"><i class="fa fa-times"></i></a>-->
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <table class="table table-bordered ">
                    <thead>
                    <tr>
                        <th><?php echo __('STT')?></th>
                        <th><?php echo __('games name')?></th>
                        <th><?php echo __('status')?></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($gamesCollection as $game):?>
                        <?php
                        if($game['game-status'] == 1){
                            $class = 'label-success';
                            $gameStatus = __('enable');
                        }else{
                            $class = 'label-important';
                            $gameStatus = __('disable');
                        }
                        ?>
                        <tr>
                            <td><?php echo $id ?></td>
                            <td><?php echo $game['game_name'] ?></td>
                            <td><span class="label <?php echo $class?>"><?php echo $gameStatus ?></span></td>
                            <td>
                                <div class="btn-group">
                                    <a href="#"><?php echo __('edit times')?></a>
                                </div>
                            </td>
                        </tr>
                        <?php $id++ ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="widget-foot">
                <ul class="pagination pull-right">
                    <li><a href="#">Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
</div>
</div><!--/ Matter ends -->
