<!--TrangVT-->
<?php
$singleTime = $this->singleTime;
$time_id = $singleTime['time_id'];

?>
<div class="col-md-7">
    <?php if (isset($this->messages)): ?>
        <?php if (is_array($this->messages)): ?>
            <div class="alert alert-warning">
                <?php foreach ($this->messages as $filed => $arr_mess): ?>
                    <?php foreach ($arr_mess as $mess): ?>
                            <span style="display: block;"> <?php echo __($mess) ?> </span>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        <?php else: ?>
            <div class="alert alert-success">
                <?php echo $this->messages ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    <div class="widget wred">
        <div class="widget-head">
            <div class="pull-left"><?php if($time_id){echo __('edit time');}else{echo __('add new time');}?></div>
            <div class="widget-icons pull-right">
                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="widget-content">
            <div class="padd">

                <div class="form quick-post">
                    <form class="form-horizontal" role="form" action="<?php echo $this->baseUrl('admin/times/update/id/'.$time_id); ?>" method="post">
                        <input type="hidden" name="time_id" value="<?php echo $singleTime['time_id'] ?>"/>
                        <!--Weekend-->
                        <div class="form-group">
                            <label class="control-label col-lg-2"><?php echo __('weekend') ?></label>
                            <div class="col-lg-7">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" <?php if($singleTime['is_weekend']){echo 'checked';}?>> <?php echo __('is weekend') ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <!-- Time Status -->
                        <div class="form-group">
                            <label class="control-label col-lg-2"><?php echo __('status')?></label>
                            <div class="col-lg-7">
                                <div class="radio">
                                    <label><input type="radio" name="<?php echo "time_status" ?>" id="1" value="1" <?php if($singleTime['time_status'] == 1){echo 'checked';}?>><?php echo __('enable')?></label>
                                </div>
                                <div class="radio">
                                    <label><input type="radio" name="<?php echo "time_status" ?>" id="0" value="0" <?php if($singleTime['time_status'] == 0){echo 'checked';}?>><?php echo __('disable')?></label>
                                </div>
                            </div>
                        </div>
                        <!-- Buttons -->
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-9 col-lg-offset-2">
                                <button type="submit" class="btn btn-info">Save Now</button>
                                <button type="reset" class="btn btn-default">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>


</div>