<div class="left col-md-6">
    <form>
        <div class="col-md-6 left-left">
            <h4>CONTACT</h4>
            <label>First Name</label>
            <input type="text" />
            <label>Contact No</label>
            <input type="text" />
            <label>Reasons To Contact</label>
        </div>
        <div class="col-md-6 left-right">

            <label>Last Name</label>
            <input type="text" />
            <label>Email Address</label>
            <input type="text" />
            <textarea></textarea>
            <input type="submit" value="SUBMIT"/>
        </div>
    </form>
</div>
<div class="right col-md-6">
    <div class="info">
        <div class="social">
            <img src="<?php echo BaseUrl_Template_Default(); ?>/_/component/images/Decode/icon/fb.png" alt="facebook">
            <img src="<?php echo BaseUrl_Template_Default(); ?>/_/component/images/Decode/icon/glasses.png" alt="Glasses">
        </div>
        <ul>
            <li class="contact-email"><span>:info@decodetv.com</span><li>
            <li class="contact-phone"><span>:+84. ...</span><li>
            <li class="contact-room"><span>:room ...</span><li>
        </ul>
    </div>

</div>