<!-- Page heading -->
<div class="page-head">
    <!-- Page heading -->
    <h2 class="pull-left">Settings
        <!-- page meta -->
        <span class="page-meta">Something Goes Here</span>
    </h2>
    <!-- Breadcrumb -->
    <div class="bread-crumb pull-right">
        <a href="<?php echo $this->baseUrl('admin') ?>"><i class="fa fa-home"></i> Home</a> 
        <!-- Divider -->
        <span class="divider">/</span> 
        <a href="javascript:void(0)" class="bread-current">Settings</a>
    </div>
    <div class="clearfix"></div>
</div> <!--/ Page heading ends -->
<!-- Matter -->

<div class="matter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="widget wred">
                    <div class="widget-head">
                        <div class="pull-left">Tables</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a> 
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <table class="table table-bordered ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Location</th>
                                    <th>Age</th>
                                    <th>Education</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Ashok</td>
                                    <td>India</td>
                                    <td>23</td>
                                    <td>B.Tech</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Kumarasamy</td>
                                    <td>USA</td>
                                    <td>22</td>
                                    <td>BE</td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Babura</td>
                                    <td>UK</td>
                                    <td>43</td>
                                    <td>PhD</td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>Ravi Kumar</td>
                                    <td>China</td>
                                    <td>73</td>
                                    <td>PUC</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Santhosh</td>
                                    <td>Japan</td>
                                    <td>43</td>
                                    <td>M.Tech</td>
                                </tr>                                                                        
                            </tbody>
                        </table>
                    </div>
                    <div class="widget-foot">
                        <ul class="pagination pull-right">
                            <li><a href="#">Prev</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">Next</a></li>
                        </ul>
                        <div class="clearfix"></div> 
                    </div>
                </div>   
            </div>
        </div>

    </div>
</div><!--/ Matter ends -->