<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>

    <body>
        <?php echo $this->render('html/top.php') ?>
        <!--content-->
        <div class="content">
            <!-- Sidebar -->
            <div class="sidebar">
                <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
                <div class="sidebar-inner">
                    <!-- Search form -->
                    <div class="sidebar-widget">
                        <form >
                            <input type="text" class="form-control" placeholder="Search">
                        </form>
                    </div>
                    <!--- Sidebar navigation -->
                    <!-- If the main navigation has sub navigation, then add the class "has_submenu" to "li" of main navigation. -->
                    <ul class="navi">
                        <!-- Use the class nred, ngreen, nblue, nlightblue, nviolet or norange to add background color. You need to use this in <li> tag. -->

                        <li class="nred current"><a href="index.html"><i class="fa fa-desktop"></i> Dashboard</a></li>
                        <!-- Menu with sub menu -->
                        <li class="has_submenu nlightblue">
                            <a href="#">
                                <!-- Menu name with icon -->
                                <i class="fa fa-th"></i> Widgets 
                                <!-- Icon for dropdown -->
                                <span class="pull-right"><i class="fa fa-angle-right"></i></span>
                            </a>
                            <ul>
                                <li><a href="widgets1.html">Widgets #1</a></li>
                                <li><a href="widgets2.html">Widgets #2</a></li>
                            </ul>
                        </li>
                        <li class="ngreen"><a href="charts.html"><i class="fa fa-bar-chart-o"></i> Charts</a></li>
                        <li class="norange"><a href="ui.html"><i class="fa fa-sitemap"></i> UI Elements</a></li>
                        <li class="has_submenu nviolet">
                            <a href="#">
                                <i class="fa fa-file-o"></i> Pages #1
                                <span class="pull-right"><i class="fa fa-angle-right"></i></span>
                            </a>
                            <ul>
                                <li><a href="calendar.html">Calendar</a></li>
                                <li><a href="post.html">Make Post</a></li>
                                <li><a href="login.html">Login</a></li>
                                <li><a href="register.html">Register</a></li>
                                <li><a href="statement.html">Statement</a></li>
                                <li><a href="error-log.html">Error Log</a></li>
                                <li><a href="support.html">Support</a></li>
                            </ul>
                        </li> 
                        <li class="has_submenu nblue">
                            <a href="#">
                                <i class="fa fa-file-o"></i> Pages #2
                                <span class="pull-right"><i class="fa fa-angle-right"></i></span>
                            </a>
                            <ul>
                                <li><a href="error.html">Error</a></li>
                                <li><a href="gallery.html">Gallery</a></li>
                                <li><a href="grid.html">Grid</a></li>
                                <li><a href="invoice.html">Invoice</a></li>
                                <li><a href="media.html">Media</a></li>
                                <li><a href="profile.html">Profile</a></li>
                            </ul>
                        </li> 
                        <li class="nred"><a href="forms.html"><i class="fa fa-list"></i> Forms</a></li>
                        <li class="nlightblue"><a href="tables.html"><i class="fa fa-table"></i> Tables</a></li>
                    </ul>
                    <!--/ Sidebar navigation -->

                    <!-- Date -->
                    <div class="sidebar-widget">
                        <div id="todaydate"></div>
                    </div>
                </div>
            </div>
            <!-- Sidebar ends -->
            <!-- Main bar -->
            <div class="mainbar">
                <?php echo $this->layout()->content; ?>
            </div><!--/ Mainbar ends -->	
            <div class="clearfix"></div>
        </div>
        <!--endcontent-->
        <?php echo $this->render('html/footer.php') ?>
    </body>
</html>
