<div class="container">
    <div class="row">
        <h4>What is DECODE?</h4>
        <p>
            • DECODE is a real-life escape game where teams of 2-5 players have to race against the clock and escape from a locked room (or rooms) using brainpower and teamwork. There are no hard and/or dangerous physical activities involved. <br/>
            • DECODE is founded with the sole mission to bring challenging, brain-stimulating and adrenaline-pumping games for people to have fun with their friends and family. <br/>
            • We now have 4 themes available, which we will change periodically to keep the excitement fresh. <br/>
            • To learn more about our game and to book, just click Booking on our website.
        </p>
    </div>
    <div class="row">
        <h4>Why DECODE?</h4>
        <p>
            • DECODE prioritizes the element of fun and seeks to provide you the most memorable hours with your beloveds. <br/>
            • Our prices are highly affordable – 40% lower than the industry average in Malaysia, Singapore, London and elsewhere! <br/>
            • Our Game Masters will make sure you are properly looked after from the time of your arrival, until after your escape. You will receive a detailed 5, you will receive a FREE Polaroid picture of your team with our DECODE backdrop. <br/>
            • DECODE highlights your intelligence with other people: we keep a public display of TOP 5 WEEKLY CHAMPIONS for each room. Your names might be up on this prestigious dean list!
        </p>
    </div>
    <div class="row">
        <h4>Which Room should I play first?</h4>
        <p>
            • Each room has a different difficulty level, which we stated along our 
            poster. If you are a first timer, we highly recommend you to start from our easiest room – you will have a much better chance of winning our complicated puzzles! 
            • Some room themes such as The Butchery and Haunted Hotel have a horror factor so if you are not the lionhearted type, go for other themes!
            • Of course, if you are particularly interested in a room theme, no harms trying out!
        </p>
    </div>
</div>